import { Brain, MessageSquare, Palette, Settings, Wrench, TrendingUp } from "lucide-react";

const blocks = [
  {
    icon: Brain,
    title: "Prompt Engineering for Real Estate",
    bullets: ["Craft prompts that return listing-ready copy", "Avoid generic 'robot' messaging", "Build reusable prompt templates for every scenario"],
  },
  {
    icon: MessageSquare,
    title: "Follow-Up + Client Communication",
    bullets: ["Text/email scripts in your voice using AI", "Objection handling and appointment setting prompts", "Automated drip sequence frameworks"],
  },
  {
    icon: Palette,
    title: "Content in Minutes",
    bullets: ["Reels hooks + captions generated by AI", "Repurposing system from one topic into 5 posts", "AI-assisted market update newsletters"],
  },
  {
    icon: Settings,
    title: "AI Automation + Smart Pipelines",
    bullets: ["AI-assisted pipeline habits that prevent lead leakage", "Trigger-based follow-up sequences", "Task prioritization using AI scoring"],
  },
  {
    icon: Wrench,
    title: "AI Tools Walkthrough",
    bullets: ["Hands-on with ChatGPT, Claude, and Gemini", "Choosing the right AI tool for each task", "Free vs. paid tools: what's worth it"],
  },
  {
    icon: TrendingUp,
    title: "AI-Powered Lead Scoring + Market Insights",
    bullets: ["Using AI to prioritize your hottest leads", "Generating neighborhood summaries and market snapshots", "CMA talking points in seconds"],
  },
];

const WhatYoullLearn = () => (
  <section id="learn" className="section-padding relative">
    <div className="mx-auto max-w-6xl">
      <div className="mx-auto max-w-3xl text-center">
        <span className="section-kicker justify-center">Curriculum</span>
        <h2 className="mt-4 text-3xl font-bold tracking-tight text-foreground sm:text-4xl">What You'll Learn</h2>
      </div>
      <div className="stagger-fade mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {blocks.map(({ icon: Icon, title, bullets }) => (
          <div key={title} className="section-frame p-6">
            <div className="flex items-center gap-3">
              <div className="drift-float flex h-11 w-11 items-center justify-center rounded-xl border border-accent/25 bg-accent/13">
                <Icon className="h-5 w-5 text-accent" />
              </div>
              <h3 className="text-base font-semibold leading-snug text-foreground">{title}</h3>
            </div>
            <ul className="mt-4 space-y-2">
              {bullets.map((b) => (
                <li key={b} className="flex items-start gap-2 text-sm leading-relaxed text-muted-foreground">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                  {b}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <p className="meta-copy mt-8 text-center text-[0.68rem] font-medium uppercase tracking-[0.09em] text-muted-foreground">
        You'll also receive: Prompt Pack + AI Tool Guide + Templates + Checklist
      </p>
    </div>
  </section>
);

export default WhatYoullLearn;
