import { Brain, MessageSquare, Palette, Settings, Wrench, TrendingUp } from "lucide-react";

const blocks = [
  {
    icon: Brain,
    title: "Prompt Engineering for Real Estate",
    bullets: ["Craft prompts that return listing-ready copy", "Avoid generic 'robot' messaging", "Build reusable prompt templates for every scenario"],
  },
  {
    icon: MessageSquare,
    title: "Follow-Up + Client Communication",
    bullets: ["Text/email scripts in your voice using AI", "Objection handling and appointment setting prompts", "Automated drip sequence frameworks"],
  },
  {
    icon: Palette,
    title: "Content in Minutes",
    bullets: ["Reels hooks + captions generated by AI", "Repurposing system from one topic into 5 posts", "AI-assisted market update newsletters"],
  },
  {
    icon: Settings,
    title: "AI Automation + Smart Pipelines",
    bullets: ["AI-assisted pipeline habits that prevent lead leakage", "Trigger-based follow-up sequences", "Task prioritization using AI scoring"],
  },
  {
    icon: Wrench,
    title: "AI Tools Walkthrough",
    bullets: ["Hands-on with ChatGPT, Claude, and Gemini", "Choosing the right AI tool for each task", "Free vs. paid tools: what's worth it"],
  },
  {
    icon: TrendingUp,
    title: "AI-Powered Lead Scoring + Market Insights",
    bullets: ["Using AI to prioritize your hottest leads", "Generating neighborhood summaries and market snapshots", "CMA talking points in seconds"],
  },
];

const WhatYoullLearn = () => (
  <section id="learn" className="section-padding bg-muted/50 ai-grid-bg">
    <div className="mx-auto max-w-5xl">
      <h2 className="text-center text-2xl font-bold tracking-tight sm:text-3xl text-foreground">
        What You'll Learn
      </h2>
      <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {blocks.map(({ icon: Icon, title, bullets }) => (
          <div key={title} className="rounded-lg border border-border bg-card p-6">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-md bg-accent/10 float-icon">
                <Icon className="h-5 w-5 text-accent" />
              </div>
              <h3 className="text-base font-semibold text-foreground">{title}</h3>
            </div>
            <ul className="mt-4 space-y-2">
              {bullets.map((b) => (
                <li key={b} className="flex items-start gap-2 text-sm text-muted-foreground">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                  {b}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <p className="mt-8 text-center text-sm font-medium text-foreground">
        You'll also receive: Prompt Pack + AI Tool Guide + Templates + Checklist
      </p>
    </div>
  </section>
);

export default WhatYoullLearn;
